### ISSUE TITLE
UFC Entry Path

### ISSUE THREAD

**Issue by PortuggeePrince** [compil3/pcn-snek#5]
Need to simplify the process for users who only want the UFC permissions (bot, Auto role etc).

**Comment by PortuggeePrince** [comment]
create a master channel and with 2 buttons UFC & Verification.

**Comment by PortuggeePrince** [comment]
right now they are having to sign up on the site, but we dont operate on the site. very cumbersome

**Comment by compil3** [comment]
Added here
903ec828e23f567221e6c73c3afa0382919f9eff
